interface: ovs_eth1
interval: 1
trigger: 4.0
recover: 2.0
trigger_count: 3
recover_count: 60
connection_hold_seconds: 300

connection:
  enable: true
  immediate_limit: true
  monitor_local_ports: [16666]
  ignore_remote_ports: [22, 51413]
  ignore_local_ports: []

bandwidth_fallback:
  enable: false

qb:
  enable: true
  url: http://192.168.5.202:8080
  user: YOUR_QB_USER
  pass: YOUR_QB_PASSWORD
  limit: 2048
  normal: 0

tr:
  enable: true
  host: 192.168.5.203
  port: 9091
  user: YOUR_TR_USER
  pass: YOUR_TR_PASSWORD
  limit: 1024
  normal: 0

notify:
  enable: false
