services:
  media-guard:
    build: .
    container_name: media-guard
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
      - /volume1/docker/lucky/logs:/lucky/logs:ro
    environment:
      - TZ=Asia/Shanghai
